### ISSUE TITLE
It's not removing the `layerBoundsObserver` correctly in iOS 11

### ISSUE THREAD

**Issue by abufaeys** [whitesmith/WSTagsField#101]
### Which version of the WSTagsField are you using? 
3.1

### On which platform does the issue happen? 
iOS11

### Are you using Carthage? 
no

### Are you using Cocoapods? 
1.5.3

### Which version of Xcode are you using? 
Xcode 9.4.1
Build version 9F2000

### What did you do?
 its good idea to  remove Observer in ios 11 , please check .
https://stackoverflow.com/questions/46782372/ios-11-what-the-kvo-is-retaining-all-observers-of-this-object-if-it-crashes-an
```
code :
deinit {
        if ProcessInfo.processInfo.operatingSystemVersion.majorVersion < 11,let observer = layerBoundsObserver {
            print("removeObserver")
            removeObserver(observer, forKeyPath: "layer.bounds")
        }

we need to remove Observer in ios 11 ,so i change the code to 

deinit {
        if let observer = layerBoundsObserver {
            print("removeObserver")
            removeObserver(observer, forKeyPath: "layer.bounds")
        }

thank  you

**Comment by hunasdf** [comment]
+1
Sometimes I got KVO_IS_RETAINING_ALL_OBSERVERS_OF_THIS_OBJECT_IF_IT_CRASHES_AN_OBSERVER_WAS_OVERRELEASED_OR_SMASHED crash. I edited the deinit function to 
```
deinit {
        if let observer = self.layerBoundsObserver {
            removeObserver(observer, forKeyPath: "layer.bounds")
            observer.invalidate()
        }
//        if ProcessInfo.processInfo.operatingSystemVersion.majorVersion < 11, let observer = layerBoundsObserver {
//            removeObserver(observer, forKeyPath: "layer.bounds")
//        }
    }
```

and evertything works good! :)

**Comment by ricardopereira** [comment]
@hunasdf @abufaeys Thank you!

I was convinced that iOS 11 and later would remove the `observer` automatically but if that doesn't work then I'll change the code.

**Comment by ricardopereira** [comment]
- [ ] Other observers should be checked.

**Comment by ricardopereira** [comment]
@abufaeys Please check the latest version.

**Comment by mozeryansky** [comment]
@ricardopereira Were you able to solve this crash?

**Comment by ricardopereira** [comment]
@mozeryansky Isn't is solved? Still happens? If so please open a new issue.
