### ISSUE TITLE
Keyboard changes automatically while deleting/selecting tags.

### ISSUE THREAD

**Issue by rajendersha** [whitesmith/WSTagsField#102]
### Which version of the WSTagsField are you using? 
its latest one

### On which platform does the issue happen? 
iOS11.4.1

### Are you using Carthage? 
No

### Are you using Cocoapods? 
No

### Which version of Xcode are you using? 
xCode 9.4

### What did you do?
Following is use case to reproduce this bug:

Set keyboard type to 'phonePad' of the WSTagsField. Then add some tags into the same field, now when selecting tags by tap or deleting them keyboard changes between standard and numeric type.

I think this is happening due to tag selection as UITextField will be resigning from first responder.

### What did you expect to happen?
Keyboard should not change automatically.

### What happened instead?
Keyboard changes automatically while deleting tags in case keyboard type is set to 'phonePad'.

**Comment by ricardopereira** [comment]
@rajendersha Thanks! Could you add a reproducible project example or at least a stack trace to get any information of the crash, please? 👍

**Comment by ricardopereira** [comment]
@rajendersha Bump.

**Comment by ricardopereira** [comment]
We finally fixed this issue: https://github.com/whitesmith/WSTagsField/releases/tag/5.1.0

**Comment by tristanmellett** [comment]
Ricardo,

Thank you very much for your hard work and dedication to accomplishing and
fixing this!

Regards,
T
