### ISSUE TITLE
Crash open/close viewcontroller modal

### ISSUE THREAD

**Issue by amatig** [whitesmith/WSTagsField#103]
### Which version of the WSTagsField are you using? 
3.1.0

### On which platform does the issue happen? 
iOS11

### Are you using Cocoapods? 
1.5.3

### Which version of Xcode are you using? 
Xcode 9.4.1
Build version 9F2000

### What did you do?
I have used a code like the example. A View IBOutlet where I add the WSTag.
This is on a ViewController opened on modal, storyboard with segue.
If I repeat open and close same time the component crash. A problem related to bad access memory when assign frame to textfield into wstag.

**Comment by ricardopereira** [comment]
@amatig Thank you for opening the issue. Please, could you add a reproducible project example or at least a stack trace to get any information of the crash? 👍

**Comment by amatig** [comment]
https://ibb.co/jZKYPp

If you change the example code to open a viewcontroller embedded in a navigation bar, with a close button, and you open and close you receive a crash on UIApplication delegate.

**Comment by ricardopereira** [comment]
@amatig Thanks, I'll look at those.

**Comment by amatig** [comment]
Now it works

**Comment by ricardopereira** [comment]
@amatig with the latest fix works?
