### ISSUE TITLE
Getting the string value from the text field?

### ISSUE THREAD

**Issue by boldlion** [whitesmith/WSTagsField#111]
I've read previous questions but I didn't quite understand how to get the string value. I tried the following but it returns an empty string:

```
cell.labelsField.onDidAddTag = { [weak self] _, _ in
      if let label = cell.labelsField.text {
          print(label)
          self?.labels.append(label)
     }
}
```

I want to able to get each value the user enters and then add it to an array. How can I do that?

**Comment by ricardopereira** [comment]
@boldlion If you need an array of String then you can do `tagsField.tags.map({$0.text})`.

Even so, you can have access the value using the `tag` attribute sent to **`onDidAddTag`**:

```swift
cell.labelsField.onDidAddTag = { [weak self] field, tag in
    self?.labels.append(tag.text)
}
```
