### ISSUE TITLE
Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <_NSKeyValueObservation 0x600001be8150> for the key path "layer.bounds" from <WSTagsField.WSTagsField 0x7fad1b119000> because it is not registered as an observer.'

### ISSUE THREAD

**Issue by mroffmix** [whitesmith/WSTagsField#119]
iOS 13 beta 3 
Xcode Version 11.0 beta (11M336w)

Looks like this issue happens during removeObserver into deist of class WSTagsField
` deinit {
        if let observer = layerBoundsObserver {
            removeObserver(observer, forKeyPath: "layer.bounds")
            observer.invalidate()
        }
    }
`

<img width="710" alt="Screen Shot 2019-07-16 at 3 21 31 PM" src="https://user-images.githubusercontent.com/6120645/61286979-6d9b0e00-a7dd-11e9-820a-d8648add93d6.png">

**Comment by ricardopereira** [comment]
@mroffmix Thanks. I’ll have a look.

**Comment by RafaelKayumov** [comment]
Any progress on this yet?

**Comment by beingbarath** [comment]
Any Progress. I am facing the same issue

**Comment by mroffmix** [comment]
just do these changes to WSTagsField.swift
` deinit {
        if #available(iOS 13, *) {
        } else {
            if let observer = layerBoundsObserver {
                removeObserver(observer, forKeyPath: "layer.bounds")
                observer.invalidate()
            }
        }
    }`

**Comment by ricardopereira** [comment]
Folks, this is already fixed in `master` https://github.com/whitesmith/WSTagsField/commit/3776d5d9ec925fafa813882ae2e9270a92507a45

A release will be out tomorrow when the final Xcode 11 is out.
