### ISSUE TITLE
remove autocorrection

### ISSUE THREAD

**Issue by amatig** [whitesmith/WSTagsField#120]
Latest version.

I have disabled every think about autocorrection but the system still show the suggestion above the keyboard.
This happen then you press back to remove the tag and wstagsfield select a tag. 

https://imgshare.io/image/lOEHK

**Comment by ricardopereira** [comment]
@amatig Can you share your code about `WSTagsField`? What are your settings?

**Comment by ricardopereira** [comment]
@amatig Please reopen this issue if this is still happening. Thank you
