### ISSUE TITLE
Keyboard Appearance reverting to default on delete

### ISSUE THREAD

**Issue by tristanmellett** [whitesmith/WSTagsField#121]
### Which version of the WSTagsField are you using? 
E.g. `1.0.11`

### On which platform does the issue happen? 
iOS11

### Are you using Cocoapods? 
Yes, up to date version

### Which version of Xcode are you using? 
Xcode 11.0

### What did you expect to happen?
I expect the keyboard to stay what Ive set it to. ie, maintain .dark appearance

### What happened instead?
When deleting a WSTagField the keyboard reverts to default keyboard.

**Comment by tristanmellett** [comment]
![67293126_333015420941033_3588343754450272256_n](https://user-images.githubusercontent.com/43564942/62035065-41947980-b22e-11e9-8c9d-99c56d573fb3.png)
![67736964_367694037227135_3556724445735288832_n](https://user-images.githubusercontent.com/43564942/62035067-41947980-b22e-11e9-99f2-fba6ad4459b5.png)

**Comment by ricardopereira** [comment]
@tristanmellett Could you add more details please?

> Which version of the WSTagsField are you using?
> On which platform does the issue happen?
> What did you expect to happen?
> What happened instead?

**Comment by tristanmellett** [comment]
On which platform does the issue happen?
       The issue is occurring on IOS. When using Xcode.
Which version of the WSTagsField are you using?
       I am using the most up to date version of WSTagsField (I believe 5.0.0)
What did you expect to happen?
       I would like the keyboard to maintain the same the entire time (.dark) with the word assists.
What happened instead?
       It is converting to the white keyboard with the word assist.

**Comment by ricardopereira** [comment]
@tristanmellett on which iOS version?

But it's you that is changing the colors of the TagsField right?
Can you share an example project or snippet code to reproduce the issue?

**Comment by tristanmellett** [comment]
@ricardopereira on iOS 12.0

I am happy with the tags field colour. The keyboard appearance is changing and I don't want that to happen.

tagsField.frame = tags.bounds
        tags.addSubview(tagsField)
        tags.backgroundColor = .clear
        tagsField.cornerRadius = 3.0
        tagsField.spaceBetweenLines = 5
        tagsField.spaceBetweenTags = 10
        tagsField.layoutMargins = UIEdgeInsets(top: 2, left: 6, bottom: 2, right: 6)
        tagsField.contentInset = UIEdgeInsets(top: 10, left: 10, bottom: 10, right: 10)
        tagsField.textColor = .white
        tagsField.placeholderColor = .lightGray
        tagsField.fieldTextColor = .lightGray
        tagsField.placeholder = "Tags:"
        tagsField.keyboardAppearance = .dark
        tagsField.returnKeyType = .default
        tagsField.tintColor = .darkGray
        tagsField.backgroundColor = .clear
        tagsField.enableScrolling = true
        tagsField.delimiter = ","
        tagsField.font = descriptionText.font
        tagsField.acceptTagOption = .space

this is what im currently using to setup my tag field. as you can see I've set the keyboardAppearance to .dark. Why then is it reverting to .default when I delete?

**Comment by tristanmellett** [comment]
@ricardopereira have you figured out why its doing this still?

**Comment by ricardopereira** [comment]
I finally fixed it! Thank you for your patience. A new release will be out soon.

**Comment by ricardopereira** [comment]
New version is out https://github.com/whitesmith/WSTagsField/releases/tag/5.1.0
