### ISSUE TITLE
Feature Request: cornerRadius of TagViews

### ISSUE THREAD

**Issue by herschel1105** [whitesmith/WSTagsField#122]
I wish there was a way to change the radius of tag views!!!
But I love this TagsFields so much!!!

**Comment by ricardopereira** [comment]
@herschel1105 You can change the radius using `tagsField.cornerRadius = 3.0` 😊

**Comment by gabser10** [comment]
Hi, I get Ambiguous use of 'cornerRadius'
 - SDWebImage (4.4.7):
    - SDWebImage/Core (= 4.4.7)
I must update?
Thank you

**Comment by ricardopereira** [comment]
@gabser10 `SDWebImage` is not related with `WSTagsField`.

**Comment by gabser10** [comment]
Hi, sorry I missed the right line from Podfile.lock :(

WSTagsField (5.0.0)

Sorry for the mistake

Thank You


Il giorno 3 feb 2020, alle ore 03:08, Ricardo Pereira <notifications@github.com<mailto:notifications@github.com>> ha scritto:


@gabser10<https://github.com/gabser10> SDWebImage is not related with WSTagsField.
