### ISSUE TITLE
XCode 11.0, Swift 5.0 (Memory and Cpu usage 100%), app crashed or stucked

### ISSUE THREAD

**Issue by jitendraIntesols** [whitesmith/WSTagsField#126]
### Which version of the WSTagsField are you using? 
E.g. `1.0.11`

### On which platform does the issue happen? 
iOS 13

### Are you using Carthage? 
No

### Are you using Cocoapods? 
1.6.0

### Which version of Xcode are you using? 
Xcode 11.0

### What did you expect to happen?

How to fix it?
app crash on real iPhone device and simulator app stucked

**Comment by EugeneEl** [comment]
I've found the reason of this issue. It happens due to infinite layout loop.

Go to the Product menu, hold down Option, and choose “Run…”
Select the Arguments tab, and click + to add a new entry
For iOS apps enter -UIViewLayoutFeedbackLoopDebuggingThreshold 100

**Comment by ricardopereira** [comment]
@EugeneEl @jitendraIntesols Could you share a snippet code or an example project to be able to reproduce the issue?
