### ISSUE TITLE
Package.swift has incorrect platform version

### ISSUE THREAD

**Issue by megajess** [whitesmith/WSTagsField#129]
### Which version of the WSTagsField are you using? 
E.g. `5.2.0`

### On which platform does the issue happen? 
E.g. `< iOS 13.0`

### Are you using Carthage? 
no

### Are you using Cocoapods? 
no

### Which version of Xcode are you using? 
(`11.2`)

### What did you do?
I added WSTagsField as a new Package Dependency and when I compile I get an error that the minimum iOS version for WSTagsField is iOS 13. Upon looking at the Package.swift file I see the platform is listed as 13, but in the wiki it states iOS 9 in the minimum. I have used this library before but with Carthage and had no problems targeting platforms < iOS 13.
```
platforms: [
        .iOS(.v13)
    ],
```

### What did you expect to happen?
For it to compile.

### What happened instead?
It did not compile.

**Comment by ricardopereira** [comment]
@megajess Thanks, it makes sense.

**Comment by ricardopereira** [comment]
Fixed on v5.3.1.
