### ISSUE TITLE
Become First Responder doesn't work

### ISSUE THREAD

**Issue by johnharutyunyan** [whitesmith/WSTagsField#136]
Thank you very much for this lib, it's amazing!
I need to open keyboard when VC is loaded, but **tagsField.becomeFirstResponder()**
 doesn't work. 
Can you please help me?

**Comment by ricardopereira** [comment]
@johnharutyunyan Could you please fill the necessary info for each issue:

### Which version of the WSTagsField are you using?

### On which platform does the issue happen?

### Are you using Carthage?
### Are you using Cocoapods?
### Which version of Xcode are you using?

**Comment by ricardopereira** [comment]
Close because of inactivity.
