### ISSUE TITLE
Manage multiple WSTagsField with one delegate

### ISSUE THREAD

**Issue by Geoffrey63** [whitesmith/WSTagsField#138]
I have to manage multiple WSTagsField on the same viewController with the same UITextFieldDelegate.
I need different actions (in textFieldShouldReturn and textFieldDidBeginEditing) depending on the UITextField edited.
How can I achieve this as the WSTagsField.textField is set to fileprivate ?
Thanks for your reply.

**Comment by ricardopereira** [comment]
The `WSTagsField.textField` has been exposed for public access in v5.3. Thanks for the issue.
