### ISSUE TITLE
Modify access levels to allow more flexible subclassing

### ISSUE THREAD

**Issue by attheodo** [whitesmith/WSTagsField#139]
### Problem description

`WSTagsField`s API for the most part is open to modifications by exposing most of it's methods as public. However for better leveraging the core functionality of the library, and especially providing custom tokenization by overriding `tokenizeTextFieldText()`, the `textField` property needs to be made `public`. Consequently the `BackSpaceDetectingTextField()` needs to be accessible outside of the module.

### Preferred solution

Make the above properties and class `public`.

**Comment by ricardopereira** [comment]
The `WSTagsField.textField` has been exposed for public access in v5.3. Thanks for the issue.

**Comment by attheodo** [comment]
Thank you for the effort man.
