### ISSUE TITLE
How to set tag limit in WSTagsField ?

### ISSUE THREAD

**Issue by arunpandiyanp** [whitesmith/WSTagsField#155]
I tried to set tag limit in  wstagsfield , for example i set 5 tags i maximum like that , i cannot find that option can you please anyone help ?

**Comment by ricardopereira** [comment]
@arunpandiyanp Did you tried check the maximum number of tags inside the `tagsField.onValidateTag` event? You can return `false` is the number of tags is above your limit. It might work.

**Comment by chroidd** [comment]
@ricardopereira thank you so much

**Comment by arunpandiyanp** [comment]
Thank you @ricardopereira
