### ISSUE TITLE
tokenize with space

### ISSUE THREAD

**Issue by canaksoy** [whitesmith/WSTagsField#20]
any option for tokenize with both return and space?

**Comment by canaksoy** [comment]
```
public func textField(textField: UITextField, shouldChangeCharactersInRange range: NSRange, replacementString string: String) -> Bool {
        if (string == " ") {
            tokenizeTextFieldText()
            return false
        }
        return true
    }
```
is it ok?

**Comment by ricardopereira** [comment]
@canaksoy Sorry for the delay. Can you clarify your issue?

**Comment by ricardopereira** [comment]
You can always access the list of current tags with `tagsField.tags` and use it like:

<img width="194" alt="screen shot 2016-09-30 at 17 35 09" src="https://cloud.githubusercontent.com/assets/3541185/18999210/4beb8874-8734-11e6-9fa1-fef806a3de1f.png">


```
tagsField.tags.reduce("", combine: { $0 + $1.text + "\n" })

> Ricardo
Whitesmith
Portugal
Coimbra
```

**Comment by canaksoy** [comment]
its for make tag with return and space. maybe you can make an option for that.
