### ISSUE TITLE
Tap Gesture

### ISSUE THREAD

**Issue by KhalisCH** [whitesmith/WSTagsField#24]
Hello,

How to know which tag is selected when the user tap on it ?

Thank you.

**Comment by ricardopereira** [comment]
@KhalisCH Unfortunately, there is no event for that currently but it's something that we will implement in the next release. Maybe next, tuesday.

**Comment by KhalisCH** [comment]
It is possible to let the user deletes the tag when he taps on it and forbid to write in the textfield ? For exemple all the touches of the keyboard are disabled except the backspace.
