### ISSUE TITLE
Unable to set InputAccessoryView

### ISSUE THREAD

**Issue by CataD256** [whitesmith/WSTagsField#25]
Hey, I was trying to change the inputAccessoryView of the text field used by WSTagsField, but I can't figure out why it doesn't set it when I start editing the field while there are already some tags added. In any other case it works fine. Could you give me some hints?

**Comment by ricardopereira** [comment]
@CataD256 If there's no tag the `inputAccessoryView` is loaded?

**Comment by CataD256** [comment]
I managed to figure it out. IQKeyboardManager was conflicting with what I had implemented. However, there is still no straight forward way to set the input accessory view for the text field used within WSTagsField. I had to do it inside the delegate  methods by searching for the first responder.

**Comment by ricardopereira** [comment]
@CataD256 I see. We will have this in mind for the next release. Thank you.

**Comment by CataD256** [comment]
Appreciate it!

**Comment by ricardopereira** [comment]
You're welcome. Thanks for opening the issue.
