### ISSUE TITLE
Tags Aren't Correct Width

### ISSUE THREAD

**Issue by Gerst20051** [whitesmith/WSTagsField#26]
Any idea what's going on here? Feel free to ask me questions for clarification. Using SnapKit for sizing / positioning of the tag fields. I have 4 separate tag fields on the same page one below the other.

<img width="620" alt="screenshot 2016-12-11 19 37 13" src="https://cloud.githubusercontent.com/assets/235372/21084993/8e1f2dd0-bfd9-11e6-9cf1-c9be8b8c42d4.png">

**Comment by Gerst20051** [comment]
Figured Out That I Needed To Call The Following Before Calling `addTags()`.

```
view.setNeedsLayout()
view.layoutIfNeeded()
```

**Comment by ricardopereira** [comment]
This could be done automatically. Thanks for opening an issue.

**Comment by ricardopereira** [comment]
Actually, this is done automatically.
