### ISSUE TITLE
TagField Not Sized Correctly After Setting readOnly to true

### ISSUE THREAD

**Issue by Gerst20051** [whitesmith/WSTagsField#27]
It would be nice to have an easy way to hide the textfield.

**Comment by Gerst20051** [comment]
<img width="618" alt="screenshot 2016-12-11 20 08 20" src="https://cloud.githubusercontent.com/assets/235372/21085254/99e323a2-bfdd-11e6-8cb5-0d1457cc6e12.png">

**Comment by Gerst20051** [comment]
I've run out of things to try. Let me know if you have any suggestions...

**Comment by ricardopereira** [comment]
@Gerst20051 How many tags are you adding? I will try to reproduce and fix it.

**Comment by Gerst20051** [comment]
@ricardopereira that first one only had the 4 tags that you see. the last one is getting cut off.

**Comment by ricardopereira** [comment]
@Gerst20051 Could you add a short runnable sample to reproduce this issue? Thanks in advance.

**Comment by ricardopereira** [comment]
You can always call `layoutSubviews()`. The `height` is automatically updated.

**Comment by abufaeys** [comment]
i have the same bug , can you please  Let me know if you have any suggestions .
thasnks
![image uploaded from ios](https://user-images.githubusercontent.com/5054059/38524759-6b757864-3c58-11e8-81bc-d78ccc3a12c9.jpg)

**Comment by ricardopereira** [comment]
@abufaeys Which version are you using?

**Comment by ricardopereira** [comment]
If you using the latest one, then you can use the `spaceBetweenLines` and give a bigger space between each line or you can shrink the tag view using the `layoutMargins` with negative values.

**Comment by abufaeys** [comment]
last version  .

**Comment by ricardopereira** [comment]
Check my latest comment and see if that helps. Thanks

**Comment by abufaeys** [comment]
ok i will check it , thank you

**Comment by Gerst20051** [comment]
Sorry @ricardopereira that I wasn't able to get back to you on this. Will see if I can look into it again soon.
