### ISSUE TITLE
Can't Close Keyboard Using Return

### ISSUE THREAD

**Issue by Gerst20051** [whitesmith/WSTagsField#28]
How should we close keyboard when tagsField is focused and return is pressed and only when the textfield is empty?

**Comment by Gerst20051** [comment]
I've got this but it would be nice if the textfield wasn't private so that i could check the text contents...

```
tagsField.onShouldReturn = { tagsField -> Bool in
    tagsField.endEditing()
    return true
}
```

**Comment by ricardopereira** [comment]
I will have this in mind for the next release. Thanks!

**Comment by Gerst20051** [comment]
@ricardopereira thanks for the prompt responses. let me know if i can help. i might fork this and submit some pull requests and come back to this after i make further progress on some other items.
