### ISSUE TITLE
tagField padding

### ISSUE THREAD

**Issue by hammyhamza** [whitesmith/WSTagsField#3]
If we set its padding and there is no tag inside tagField then textField padding is not set. 
Try it in **WSTagsFieldExample**, just press test button without writing anything.
Everything else is working great.

**Comment by ricardopereira** [comment]
You mean this right?

![simulator_screen_shot_15_jul_2016_13_54_11](https://cloud.githubusercontent.com/assets/3541185/16874890/fbc6c5ca-4a93-11e6-9a4f-4adeff24fd1d.png)

**Comment by hammyhamza** [comment]
Great its perfect now!
