### ISSUE TITLE
Way to get text value?

### ISSUE THREAD

**Issue by sean-crowl** [whitesmith/WSTagsField#34]
Is there currently a way to access the text value of the field itself, such as using it to implement a search function via .contains before setting a tag? For example, if I wanted to allow somebody to have the text in the field compare to another string, and if it's equal, then make it a tag.

**Comment by ricardopereira** [comment]
You can try to use one of the events like `onDidChangeText` to accomplish that.

**Comment by ricardopereira** [comment]
Well, maybe it's better to have something like `onShouldAcceptTag` where you can decide if the tag is valid or not. I will have that in mind for the next release. Thanks.
