### ISSUE TITLE
how to set the tags programmatically in wstagsfield

### ISSUE THREAD

**Issue by mohammadshalhoob** [whitesmith/WSTagsField#35]
how to set the tags programmatically in wstagsfield ( not the user input) .

thanks for help .

**Comment by ricardopereira** [comment]
@mohammadshalhoob Just use the `addTags` method like `tagsField.addTags(["Whitesmith", "iOS", "iOS", "UIKit"])`.

**Comment by mohammadshalhoob** [comment]
thanks ricardopereira .
