### ISSUE TITLE
inputFieldAccessoryView with ContainerView (with UIViewController)  problem

### ISSUE THREAD

**Issue by hamzauzumcu** [whitesmith/WSTagsField#36]
Hi,
You can download example project here: https://goo.gl/iLtxY5
Issue reproduce steps;
1- Run project
2- Add one or more tag 
3- Select one tag and delete it. 

Error; 'UIViewControllerHierarchyInconsistency', reason: 'child view controller should have parent view controller:<UICompatibilityInputViewController: 0x7fc56dd4eca0> but actual parent is...

I read a lot of documents but i can't find solution.

**Comment by ricardopereira** [comment]
@hamzauzumcu Thanks. I will take a look.

**Comment by hamzauzumcu** [comment]
@ricardopereira Did you solve the issue?

**Comment by ricardopereira** [comment]
@hamzauzumcu Not yet sorry. Is this blocking you?

**Comment by hamzauzumcu** [comment]
Yes, i cant continue to develop the app

**Comment by ricardopereira** [comment]
@hamzauzumcu That error happens when you the keyboard is showing?

**Comment by ricardopereira** [comment]
Closed because of inactivity. If the problem persists, feel free to reopen the issue. Thanks.
