### ISSUE TITLE
can i delete tag by deleteing single caharacter 

### ISSUE THREAD

**Issue by sahabe1** [whitesmith/WSTagsField#41]
Can i delete tags by delete single- singe charatcer instead of delete single tags
also can i remove space between tags

**Comment by ricardopereira** [comment]
@sahabe1 Sorry, currently you can't edit tags. You have to delete the invalid tag and create a new one. You can remove the space between tags by setting `tagsField.spaceBetweenTags = 10.0`. Hope it helps.
