### ISSUE TITLE
Unable to archive app

### ISSUE THREAD

**Issue by TringRajagopal** [whitesmith/WSTagsField#43]
![wstagsfieldissue](https://cloud.githubusercontent.com/assets/24970678/25350971/90633bc0-2944-11e7-9f10-6fb37aeee466.png)

I got this issue when I try to archive my app integrated with WSTagsField framework. What can I do now? Do you have any solution for this?. It could be so helpful if you can solve the issue asap. Please let me know if any solution matches for this.

**Comment by ricardopereira** [comment]
@TringRajagopal Are you using CocoaPods?

**Comment by TringRajagopal** [comment]
@ricardopereira Thanks for the response..! Actually I was not integrated with CocoaPods. As I needed some customisation to your WSTagsField according to my use case, I have just imported your class files and added few delegates into it.

**Comment by ricardopereira** [comment]
@TringRajagopal If you imported the class files manually then I'm 100% sure that error shouldn't be happening. What steps did you do to import the swift files?
