### ISSUE TITLE
can i apped # before creating tags

### ISSUE THREAD

**Issue by sahabe1** [whitesmith/WSTagsField#44]
I want to add add # before creating tags is it possible

**Comment by ricardopereira** [comment]
@sahabe1 Do you want to show the `#` character to the user? Or is it just for internal purpose?

**Comment by sahabe1** [comment]
yes, want to show # character in tags

**Comment by ricardopereira** [comment]
@sahabe1 Well, you can try check the text and block it using the `onVerifyTag` event and add it yourself. Something like:

```swift
tagsField.onVerifyTag = { field, text in
    field.addTag("#\(text)")
    return false
}
```
