### ISSUE TITLE
Swift 3 and SwiftPM support

### ISSUE THREAD

**Issue by TofPlay** [whitesmith/WSTagsField#5]
Hi,
It's will be great to create a [Swift 3](https://swift.org/blog/swift-3-0-release-process/) version of your component 

Article about **Swift 3**: 
- [Migrating to Swift 2.3 or Swift 3 from Swift 2.2](https://swift.org/migration-guide/)

With [Swift 3](https://swift.org/blog/swift-3-0-release-process/) it would also be nice to add support for [SwiftPM](https://swift.org/package-manager/)

Articles about **SwiftPM**:
- [Package.swift — The Manifest File](https://github.com/apple/swift-package-manager/blob/master/Documentation/Package.swift.md)
- [Developing Packages](https://github.com/apple/swift-package-manager/blob/master/Documentation/DevelopingPackages.md)
- [System Modules](https://github.com/apple/swift-package-manager/blob/master/Documentation/SystemModules.md)
- [Swift Package Manager Community Proposal](https://github.com/apple/swift-package-manager/blob/master/Documentation/PackageManagerCommunityProposal.md)
 
On your `README.md` add [![SwiftPM Compatible](https://img.shields.io/badge/SwiftPM-Compatible-brightgreen.svg)](https://swift.org/package-manager/)  on top and add section for the installation with SwiftPM.

**Comment by ricardopereira** [comment]
Swift 3 is something that I'm aware of and then I will look into the SwiftPM support. Thanks.
BTW, nice issue 👍

**Comment by ricardopereira** [comment]
@TofPlay Do you already use SwiftPM? Is it stable?

**Comment by ricardopereira** [comment]
😌 (_Downloading Xcode 8 beta 2..._)

**Comment by TofPlay** [comment]
@ricardopereira 
> Do you already use SwiftPM?

Yes I use Swift for the projects I migrates Swift 3. But It's takes time because all components I used on a project must have migrated on Swift 3 and be compatible SwiftPM.

>  Is it stable?

On the projects that I could migrate yes

**Comment by ricardopereira** [comment]
**Swift 3** is now supported! 🙌
Check out the [`2.0.0.beta.1`](https://github.com/whitesmith/WSTagsField/releases/tag/2.0.0.beta.1) release.
