### ISSUE TITLE
Feature request: Autocomplete functionality

### ISSUE THREAD

**Issue by dlukianenko** [whitesmith/WSTagsField#53]
Hi there,
Could you please add functionality for autocomplete for tags. 

Also if you don't have time to do that could you describe idea how it could be implemented so I could maybe start working on that feature.

Any help, suggestions are highly appreciated.

Thank you

**Comment by ricardopereira** [comment]
@dlukianenko Thanks for opening an issue. So you want a list of available tags while typing? Can you share a mockup with the idea?

**Comment by dlukianenko** [comment]
Something like [example](http://textextjs.com/manual/examples/autocomplete-with-tags.html) You have the list of suggestions and when you type it suggest you existing tags from storage or you can just create a new one without selecting nothing from the list. 

I'm asking for this functionality because I need to have a place where users adds emails of people to whom he wants to share his post and I was thinking to have it as tag input with autocomplete with existing emails of his friends from the storage. Also he will be able to add a new email if it is not in the list from DB just typing it.

**Comment by ricardopereira** [comment]
I need to think about it. Maybe showing a `UITableView` under the field with same width and a fixed height and filter the results by the text from the field. The table is shown when the text field is not empty (maybe using the `.EditingChanged` event).

**Comment by dlukianenko** [comment]
I think this functionality will bring a good value, thank you for your response

**Comment by majid701** [comment]
@ricardopereira @dlukianenko @AgentWS 
I think this library could be used to implement it: https://github.com/apasccon/SearchTextField

I'm going to make a fork of this now and try it.
