### ISSUE TITLE
Installing with Pods 2.1.2 there is not updated

### ISSUE THREAD

**Issue by motapuma** [whitesmith/WSTagsField#58]
If i install WSTagsField using Pods, the code downloaded is not updated... it is not available the properties "maxHeight" for WSTagsField

**Comment by ricardopereira** [comment]
@motapuma Thanks for your issue. I'll create a new version this weekend.

**Comment by ricardopereira** [comment]
Version 3.0.0 (Swift 4) has been released. Thanks for your patience. https://github.com/whitesmith/WSTagsField/releases/tag/3.0.0
