### ISSUE TITLE
Use Cases When Integrating WSTagsField In Search Bar

### ISSUE THREAD

**Issue by justinguo** [whitesmith/WSTagsField#61]
I have a few questions about how to correctly integrate WSTagsField as a search field:
1) If backspace is pressed for a partially entered text, a tag with that partial text will be added automatically. Can I disable this feature? Is editing allowed when inputing the tag?
2) Is there any way to access the index of a specific that is generated?

**Comment by ricardopereira** [comment]
> If backspace is pressed for a partially entered text, a tag with that partial text will be added automatically. Can I disable this feature? Is editing allowed when inputing the tag?

@justinguo A backspace will never add a tag. Are you sure about that?

> Is there any way to access the index of a specific that is generated?

@justinguo You can use the [`onDidAddTag`](https://github.com/whitesmith/WSTagsField/blob/master/Source/WSTagsField.swift#L105) event and check the index using the created tag and comparing it with all the tags.

**Comment by justinguo** [comment]
@ricardopereira Thanks for the quick response.

For the backspace key deleting issue, I just found that it has been discussed and fixed in an un-merged pull request: Delete backwards fix #57.

For the index issue, I modify the source code of WSTag and add an id field with UUID value in the initializer. In this case it is more handy to access tag using id.

I actually have another weird issue:
Suppose I have four tags in the text field (i.e. tag A, tag B, tag C, tag D). If I use removeTag to delete the last one (Tag D), it works as expected (final result is: A, B, C). But when trying to delete tag C (either by double-clicking or backspace), the final result is A, B (in other words, the tag after C is also deleted). Ih happens also for tag B and tag A. Any clues about this issue?

Thanks again for the continual support.

**Comment by justinguo** [comment]
By the way, is there a way to know which tag is selected? Now the onDidSelectTagView only knows if a tag in the TagView is selected, but do not know which tag in it is selected. If I would like to add a property like isSelected to the WSTag object, where would be the best place to set this property? Thanks.

**Comment by ricardopereira** [comment]
> Suppose I have four tags in the text field (i.e. tag A, tag B, tag C, tag D). If I use removeTag to delete the last one (Tag D), it works as expected (final result is: A, B, C). But when trying to delete tag C (either by double-clicking or backspace), the final result is A, B (in other words, the tag after C is also deleted). Ih happens also for tag B and tag A. Any clues about this issue?

Maybe it's a bug 😐 Need to check that out.

> If I would like to add a property like isSelected

Yap, a `selectedTag` property should do it. Can you do a PR?

**Comment by justinguo** [comment]
@ricardopereira

About the duplicated tag removal issue when syncing checkmarks in a table view, now I add the tagID property using UUID() once each tag is created. In this case even two tags with the same name are different (which is helpful in cases when we need to distinguish them). Also I added more checking conditions in onDidRemoveTag() and didDeselectRowAt(). Now it works as expected.

I may submit a pull request shortly to add the tag ID and isSelectedTag property. isSelectedTag will set to false by default. In tagView.onDidRequestDelete I set isSelectedTag to true when it is removed from data. So this flag only consider the tag deletion action triggered from tapping.

**Comment by justinguo** [comment]
@ricardopereira

Thanks for the suggestion. I just submitted the PR. Added two properties: id and isSelectedToBeRemoved. Please advise if anything I am not aware of.

**Comment by justinguo** [comment]
@ricardopereira

Is there an option to disable selecting tag animation?

**Comment by ricardopereira** [comment]
Thanks for the PR! I'll take a look.

> Is there an option to disable selecting tag animation?

@justinguo No, unfortunately there's no option currently.
