### ISSUE TITLE
Begin a new line during a long text field input

### ISSUE THREAD

**Issue by justinguo** [whitesmith/WSTagsField#64]
Is there a feature to support automatically moving the active text field to a new line once the text field input is wider than the maximum available width remaining in the current line? (Just like the behavior in iOS Messages/Mail App)

Now the textfield will make horizontal scrolling on long content.

If not can this feature be supported in the future release? Thanks for the information.

**Comment by ricardopereira** [comment]
@justinguo Thanks for that issue. I see what you mean but unfortunately this isn't supported right now. Let's see if any contributor wants to implement that.

**Comment by ciccioska** [comment]
Hi, I forked the repo and I'm watching on this enhancement.

**Comment by ricardopereira** [comment]
Related to #77
