### ISSUE TITLE
how can I get the array of tags that were entered 

### ISSUE THREAD

**Issue by Azzam-RAR** [whitesmith/WSTagsField#66]
hi and thank you for the great work 
I want to grab all the tags that were entered to the scrollView and send them to firebase 
I tried the following -->      TagsField.tags.description 
but I get an array that looks like this  
theProjectName.WSTag(text: "1234"), theProjectName.WSTag(text: "abc")
how can I get only the tags like this ["1234" , "abc"]

**Comment by ricardopereira** [comment]
Sure, just use that list `field.tags.map{ $0.text }`.
