### ISSUE TITLE
does not work auto-increment cell

### ISSUE THREAD

**Issue by Qumonking** [whitesmith/WSTagsField#70]
`

    tableviewcell:
     @IBOutlet weak var tagsView: UIView!

    tableviewcontroller:

            cell = tableView.dequeueReusableCell(withIdentifier: "tagField", for: indexPath) as! AddManuallyRecipeTableViewCell

            let tagsView = cell.tagsView!
            let tagsField = WSTagsField()
            
            tagsField.frame = tagsView.bounds
            tagsView.addSubview(tagsField)
            
            tagsField.layer.cornerRadius = 3.0
            tagsField.font = .systemFont(ofSize: 14.0)
            tagsField.placeholder = "Добавить тэг ..."
            tagsField.returnKeyType = .next
            tagsField.delimiter = " "

            tagsField.onDidChangeHeightTo = { _, height in
                print("HeightTo \(height)")
                
                tableView.beginUpdates()
                tableView.endUpdates()
                
            }
`

<img width="246" alt="2018-02-21 14 02 11" src="https://user-images.githubusercontent.com/35995025/36467108-d720c244-170f-11e8-9056-4a412c88c7a2.png">

how to fix?

**Comment by ricardopereira** [comment]
@Qumonking which version are you using?

**Comment by Qumonking** [comment]
@ricardopereira  Using WSTagsField (2.1.2)

**Comment by ricardopereira** [comment]
@Qumonking where is that code being used? `tableView(UITableView, cellForRowAt: IndexPath)` from `UITableViewDataSrouce`?

**Comment by ricardopereira** [comment]
@Qumonking And you are using AutoLayout? The `Tags View` has constrains?

I'm a bit confused. What is `Tags View` type?

**Comment by Qumonking** [comment]
@ricardopereira 
I tried to create a new UIView and limited it from all sides to 0. Type Tags View : UIView!
<img width="1001" alt="2018-02-21 18 35 41" src="https://user-images.githubusercontent.com/35995025/36478207-8505a12e-1736-11e8-9193-3e8473d04328.png">

**Comment by ricardopereira** [comment]
@Qumonking Can you send me an example project or playground to reproduce this problem?

**Comment by Qumonking** [comment]
@ricardopereira yes, on email?

**Comment by Qumonking** [comment]
@ricardopereira i sent to m@ricardopereira.eu

**Comment by ricardopereira** [comment]
@Qumonking I don't see any email. Could you send it to ricardopereira[at]whitesmith.co please?

**Comment by Qumonking** [comment]
@ricardopereira I sent to ricardopereira@whitesmith.co

**Comment by Qumonking** [comment]
@ricardopereira How can I solve this problem?

**Comment by Qumonking** [comment]
My problem is still unresolved

**Comment by Qumonking** [comment]
I made a mistake
