### ISSUE TITLE
How to reduce the height of a cell?

### ISSUE THREAD

**Issue by Qumonking** [whitesmith/WSTagsField#71]
How to reduce the distance between cells?

**Comment by Qumonking** [comment]
<img width="231" alt="2018-02-26 21 03 06" src="https://user-images.githubusercontent.com/35995025/36674395-82577d8e-1b38-11e8-9ce4-b450ce6e9489.png">
![Uploading Снимок экрана 2018-02-26 в 21.03.22.png…]()

**Comment by Qumonking** [comment]
<img width="247" alt="2018-02-26 21 04 08" src="https://user-images.githubusercontent.com/35995025/36674423-9efc0496-1b38-11e8-848c-584cd4f3d0fb.png">
<img width="257" alt="2018-02-26 21 03 22" src="https://user-images.githubusercontent.com/35995025/36674427-a300ca72-1b38-11e8-9b22-f9abe41455de.png">

**Comment by Qumonking** [comment]
This happens after adding tags - cell.tagsField.addTags(tags), Where tags as [String]

**Comment by ricardopereira** [comment]
@Qumonking are you using AutoLayout?

**Comment by Qumonking** [comment]
@ricardopereira yes, only this happed

                cell.frame.size.height = height
                
                if self.check {
                    tableView.reloadData()
                }
                
                self.check = false
                
                tableView.beginUpdates()
                tableView.endUpdates()

**Comment by ricardopereira** [comment]
@Qumonking Which version are you using? Is that WSTagsField in an UITableViewCell?

**Comment by Qumonking** [comment]
@ricardopereira last version

<img width="728" alt="2018-03-06 23 48 59" src="https://user-images.githubusercontent.com/35995025/37045679-15476814-2199-11e8-8061-61fa6b7d1467.png">
<img width="742" alt="2018-03-06 23 49 10" src="https://user-images.githubusercontent.com/35995025/37045681-15708e6a-2199-11e8-8601-805a8f4b8583.png">
<img width="729" alt="2018-03-06 23 49 24" src="https://user-images.githubusercontent.com/35995025/37045682-1599b24a-2199-11e8-82e5-b100aadcd078.png">
<img width="731" alt="2018-03-06 23 49 37" src="https://user-images.githubusercontent.com/35995025/37045683-15c965d0-2199-11e8-82f6-f92815c440be.png">

**Comment by ricardopereira** [comment]
A new version has been released https://github.com/whitesmith/WSTagsField/releases/tag/3.0.0. Can you please check if this has been fixed? If not, then reopen the issue please. Thanks!
