### ISSUE TITLE
Tag view height

### ISSUE THREAD

**Issue by usmantararnxb** [whitesmith/WSTagsField#75]
Tag View auto height is not working properly.

**Comment by ricardopereira** [comment]
@usmantararnxb Which version are you using?

**Comment by ravikanhasoft** [comment]
@ricardopereira I am also facing a issue with tag height. In my case my tag text content is very big almost 2 lines. In this case it display in a single line tag and rest of the text is truncated with period. (The rest.......) So if is there any way to make the tag multiline as per the text content please help me.

**Comment by ricardopereira** [comment]
@ravikanhasoft With the latest version?

**Comment by ravikanhasoft** [comment]
@ricardopereira  Yes with a latest version.  You can see from this Screen shot.

![screen shot 2018-03-30 at 7 23 25 pm](https://user-images.githubusercontent.com/29453207/38140099-f2e474e6-344f-11e8-83ed-2532257f68f6.png)

**Comment by ricardopereira** [comment]
Oh, now I see what you mean. Thanks for your screenshot. This library isn't ready to word-wrap a tag. Sorry. Even so, I'll open an issue for that and let's see if anyone from the community wants to implement that.
