### ISSUE TITLE
Request a new release to support swift 4.0

### ISSUE THREAD

**Issue by billzhou0223** [whitesmith/WSTagsField#76]
Hey White, could you please make a new release based on swift 4.0? I saw those commits to support swift 4.0 was already in master branch.

**Comment by ricardopereira** [comment]
@billzhou0223 You're using `master` with no issue? I still need to fix #65 to create a release. That's why we didn't a new version but it makes sense to have one. What's your deadline? Just manage my time with your expectation.

**Comment by billzhou0223** [comment]
@ricardopereira I am consuming master branch and it is working fine in our project. Actually I made some changes on `WSTagsField` and `WSTagsView` and added some new api based on the requirements of our project. Not sure if this solves the issue? Anyway I will make a pull request so you can take a look.

Our next release will be on Apr 15. Thank you so much for your time.

**Comment by ricardopereira** [comment]
Version 3.0.0 (Swift 4) has been released. Thanks for your patience. https://github.com/whitesmith/WSTagsField/releases/tag/3.0.0
