### ISSUE TITLE
2.2.0 going to be released/uploaded to CocoaPods anytime soon?

### ISSUE THREAD

**Issue by JoaoManaroulas** [whitesmith/WSTagsField#79]
Title.

Asking this as it looks like in 2.2.0 you can set a max height so the view doesn't goes 2 or more lines.

Is there any way to set a maximum height for the WSTagsField on 2.1.2? Would appreciate if the view respects its superview maximum height. 

Att;

**Comment by ricardopereira** [comment]
@JoaoManaroulas Yes, it will be today. Hopefully.

> Is there any way to set a maximum height for the WSTagsField

Yes, with a height constraint.

**Comment by JoaoManaroulas** [comment]
@ricardopereira Oh, nice! Thank you 👍 

> Yes, with a height constraint.

I was thinking of something as in the 2.2.0 version, but yeah, a height constraint works.

**Comment by ricardopereira** [comment]
Version 3.0.0 (Swift 4) has been released. Thanks for your patience. https://github.com/whitesmith/WSTagsField/releases/tag/3.0.0
