### ISSUE TITLE
Unused constant (FIELD_MARGIN_X)

### ISSUE THREAD

**Issue by own2pwn** [whitesmith/WSTagsField#81]
Hi, 

Looks like there is a `FIELD_MARGIN_X` constant here but it's not used anywhere in the code.

Just wanted to draw your attention to it.

**Comment by ricardopereira** [comment]
Thanks! It has been removed in the latest version. https://github.com/whitesmith/WSTagsField/releases/tag/3.0.0) you can now define the `layoutMargins` to
