### ISSUE TITLE
Keyboard crash

### ISSUE THREAD

**Issue by own2pwn** [whitesmith/WSTagsField#85]
### Which version of the WSTagsField are you using? 
`3.1.0`

### On which platform does the issue happen? 
`iOS 11.2.1` 

### Which version of Xcode are you using? 
`Xcode 9.2`

### What did you do?
When selecting tags by tap or deleting them (so prev. gets selected) keyboard glitches first (it changes between standard and custom (Gboard in my case) ). And after some selections it becomes completely unusable. 
I've deleted other keyboard so in preferences I've left only Gboard. 

I think there's something wrong with `FirstResponder` overrides but I'm not sure. 

There's a [video](https://youtu.be/3lHX3MY1tYw). You may notice that `q` letter was added somehow. And when I've deleted all the tags keyboard got down and I can't tap any key.

### Error log: 
```
[ops] Hub connection error Error Domain=NSCocoaErrorDomain Code=4097 "connection to service named com.google.keyboard.KeyboardExtension" UserInfo={NSDebugDescription=connection to service named com.google.keyboard.KeyboardExtension}

[Touch] unexpected nil window in __sendSystemGestureLatentClientUpdate, _windowServerHitTestWindow: <UIRemoteKeyboardWindow: 0x112079800; frame = (0 0; 375 667); opaque = NO; autoresize = W+H; layer = <UIWindowLayer: 0x1c0236b40>>, touch:<UITouch: 0x111d227d0> phase: Stationary tap count: 1 force: 0.083 window: (null) view: (null) location in window: {0, 0} previous location in window: {359.99993342161002, 587.4999186396775} location in view: {0, 0} previous location in view: {0, 0}

[ops] plug-in <PKPlugin: 0x111e194d0 com.google.keyboard.KeyboardExtension(1.22.0) <UDID> 3(0) /private/var/containers/Bundle/Application/<UDID>/Gboard.app/PlugIns/Gboard.appex> pre-screen sees activating state

Unable to setup extension context - error: Couldn’t communicate with a helper application.
```

**Comment by ricardopereira** [comment]
@own2pwn I can't reproduce this in the simulator. Could you arrange me an example or give more details on how to reproduce the issue please? Thanks

**Comment by ricardopereira** [comment]
Please reopen this if it stills happens. Thanks
