### ISSUE TITLE
Animation (CGTransform) Issue

### ISSUE THREAD

**Issue by own2pwn** [whitesmith/WSTagsField#86]
### Which version of the WSTagsField are you using? 
`3.1.0`

### On which platform does the issue happen? 
`iOS 11.2.1`, `Simulator`

### Which version of Xcode are you using? 
`Xcode 9.2`

### What did you do?
When selecting any tag for the first time it's tag label gets truncated I guess due to layer's transform? You may notice that in the beginning of video I've provided in #85

**Comment by ricardopereira** [comment]
@own2pwn Thanks for the issue! Sorry, I didn't noticed what you explained. Could you share a screenshot?

**Comment by ricardopereira** [comment]
Please reopen this if it still happens. Thanks.
