### ISSUE TITLE
cant add placeholder when remove all tag

### ISSUE THREAD

**Issue by abufaeys** [whitesmith/WSTagsField#87]
### Which version of the WSTagsField are you using? 
3.1.0

### On which platform does the issue happen? 
iOS11

### Are you using Carthage? 
no

### Are you using Cocoapods? 
1.4.0

### Which version of Xcode are you using? 
Xcode 9.2
Build version 9C40b
### What did you do?
cant add placeholder when remove all tag .
Add a short snippet of code to show the problem
 self.tagView.placeholderAlwaysVisible = true
  self.tagView.placeholderColor = UIColor.lightGray
   self.tagView.placeholder = "No tag selected yet".localized()

### What did you expect to happen?
show placeholder when remove all tag .

### What happened instead?
placeholder is hidden when remove all tag .

**Comment by abufaeys** [comment]
yes it work in example app , but i don't  know why its not work in my app .
i will check my code again . 
thank you .

**Comment by ricardopereira** [comment]
@abufaeys Great. Feel free to reopen this issue if you can't find the answer/problem of yours.
