### ISSUE TITLE
How can i center align of tags?

### ISSUE THREAD

**Issue by vasylboy90** [whitesmith/WSTagsField#88]
### Which version of the WSTagsField are you using? 
3.1.0

### On which platform does the issue happen? 
iOS 11

### Are you using Carthage? 
No

### Are you using Cocoapods? 
No
I only downloaded this and run sample project.

### Which version of Xcode are you using? 
9.3

### What did you do?
How can i align center of tags?

### What did you expect to happen?
I hope to align center of tags and placeholder.

**Comment by ricardopereira** [comment]
@vasylboy90 There's now option for that at the momento Sorry. I'll have that in consideration for a future feature. Thanks.
