### ISSUE TITLE
Change Font Size

### ISSUE THREAD

**Issue by gkhanacer** [whitesmith/WSTagsField#89]
### Which version of the WSTagsField are you using? 
 WSTagsField (3.1.0)

### On which platform does the issue happen? 
iOS11

### Are you using Carthage? 
NO

### Are you using Cocoapods? 
YES 1.5.0

### Which version of Xcode are you using? 
Xcode 9.3
Build version 9E145

### What did you do?
I want to change font size of tag. I couldn't do it. Could you help me, please?

tagsField.font = UIFont(name: (tagsField.font?.fontName)!, size: 14.0)

I used it, but it didn't work.

**Comment by ricardopereira** [comment]
@gkhanacer `tagsField.font = UIFont.systemFont(ofSize: 9)` is working for me.

![simulator screen shot - iphone 6s - 2018-05-28 at 13 02 04](https://user-images.githubusercontent.com/3541185/40613651-53948c54-6277-11e8-813e-a1a0c6f82f1f.png)

**Comment by ricardopereira** [comment]
@gkhanacer Where are you adding the code?
