### ISSUE TITLE
Using WSTagField in Custom Table View.

### ISSUE THREAD

**Issue by gkhanacer** [whitesmith/WSTagsField#91]
### Which version of the WSTagsField are you using? 
`WSTagsField (3.1.0)`

### On which platform does the issue happen? 
`iOS11`

### Are you using Carthage? 
`no`

### Are you using Cocoapods? 
`1.5.0`

### Which version of Xcode are you using? 
(`Xcode 9.3`)

### What did you do?

I want to add WSTagField in a custom TableView cell.
I put a UIView and init tagField features (lineNumber = 0, etc.). Also I set the auto layout pins.
But its view does not view right. The tableviewcell height does not change. 

I set also some variables in vievDidLoad in TableView delegation class:

```
        tableView.rowHeight = UITableViewAutomaticDimension
        tableView.estimatedRowHeight = 50
```

I don't understand, what is my mistake? Do you try it in custom table view, successfully?

**Comment by ricardopereira** [comment]
@gkhanacer There's an example using TableView in the Demo app of this repository. Did you look at it? Is it what you're looking for? Thank you

**Comment by ricardopereira** [comment]
Please look at https://github.com/whitesmith/WSTagsField/blob/master/Example/WSTagsFieldExample/TableViewController.swift

Thanks!
