### ISSUE TITLE
how to get array of tags?

### ISSUE THREAD

**Issue by furqan1144** [whitesmith/WSTagsField#94]
### Which version of the WSTagsField are you using? 
E.g. `1.0.11`

### On which platform does the issue happen? 
E.g. `iOS11`

### Are you using Carthage? 
If yes, specify the version (`carthage version`)

### Are you using Cocoapods? 
If yes, specify the version (`pod --version`)

### Which version of Xcode are you using? 
(`xcodebuild -version`)

### What did you do?
Describe the problem.
```
Add a short snippet of code to show the problem
```

### What did you expect to happen?
Describe the expected outcome.

### What happened instead?
Describe what happened instead.

**Comment by furqan1144** [comment]
help..

**Comment by ricardopereira** [comment]
@furqan1144 Just use `tagsField.tags`. If you want strings then do `tagsField.tags.map{ $0.text }`.
